export const usersWithRolesState = (state) => state.myStore.usersWithRoles
export const categoriesState = (state) => state.myStore.categories
export const invoicesState = (state) => state.myStore.invoices
export const invoiceDetailsState = (state) => state.myStore.invoiceDetails
export const subCategoriesState = (state) => state.myStore.subCategories
export const urlImageUploadedState = (state) => state.myStore.urlImageUploaded
export const productItemsState = (state) => state.myStore.productItems
export const userLogedInState = (state) => state.myStore.userLogedIn
export const loginStatusState = (state) => state.myStore.loginStatus
export const productsState = (state) => state.myStore.products
export const contactsState = (state) => state.myStore.contacts